### ISSUE TITLE
[slackana-11] -The title of setting is wrong input

### ISSUE THREAD

**Issue by ipilikent** [abduljalilpalala/ps-slackana#18]
## Description

- The header title in the setting modal is different from Figma design

![Wrong header title for setting modal](https://user-images.githubusercontent.com/110364019/193186368-5b502e77-29ef-4243-9fe0-b8af5e58cb66.gif)

Figma Design

![11](https://user-images.githubusercontent.com/110364019/193186392-45388cac-e269-4fdd-b4fa-220ee7c6b418.png)

### Recreating the bug

- Click 3 dots at the bottom sidebar
- Click Profile

## Expected Behavior

- The header title should be **My Settings**

**Comment by johnpaul-sun** [comment]
I created a Bugfix PR for this issue.
https://github.com/abduljalilpalala/ps-slackana/pull/23
