### ISSUE TITLE
[slackana-14] - The status dropdown is overlaid

### ISSUE THREAD

**Issue by ipilikent** [abduljalilpalala/ps-slackana#19]
## Description 

- The filter status dropdown is overlaid on the container layout
- The At risk status it so delay to highlight

![Filter dropdown](https://user-images.githubusercontent.com/110364019/193194098-906a2421-c460-419e-89dd-d75acbb666d4.gif)

Figma Design
![13](https://user-images.githubusercontent.com/110364019/193194255-b0b3789e-d0c2-4232-a8c1-8453fd27038e.png)

### Recreating the bug

- Click Home
- Click 3 dots

## Expected Behavior

- The filter status dropdown should not be overlaid

**Comment by johnpaul-sun** [comment]
I created a Bugfix PR for this issue.
https://github.com/abduljalilpalala/ps-slackana/pull/22
