### ISSUE TITLE
The filter dropdown is not responsive

### ISSUE THREAD

**Issue by ipilikent** [abduljalilpalala/ps-slackana#24]
## Description

- The filter dropdown is overlaid 

![Dropdown Overlay](https://user-images.githubusercontent.com/110364019/193450235-8e5ed639-4962-49f2-a9b1-17a4ea30fee8.gif)

## Expected Behavior

- The filter dropdown should not be overlaid
- Filter dropdown should be responsive

**Comment by jsvelte** [comment]
Close #25
