### ISSUE TITLE
Remove excess Padding in Add Member Modal Header

### ISSUE THREAD

**Issue by ipilikent** [abduljalilpalala/ps-slackana#27]
## Description

- The project member modal has a lot of space

![Screenshot 2022-10-03 154315](https://user-images.githubusercontent.com/110364019/193528532-58948b3c-639e-413b-a2e6-0be3832a7efd.png)

## Recreating Bug

- Click Projects
- Click your Project
- Click on the avatar list pictures at top right

## Expected Behavior

-  The padding of the project member modal must be correrct

**Comment by jsvelte** [comment]
close #30
