### ISSUE TITLE
Add Little Padding in Project Header

### ISSUE THREAD

**Issue by ipilikent** [abduljalilpalala/ps-slackana#28]
## Description

- Need a little padding in the header so that there is space for the menu

![Screenshot 2022-10-03 161118](https://user-images.githubusercontent.com/110364019/193530637-e3912f7a-ebc7-4e54-a655-83a84b7307b2.png)

## Recreating Bug

- Click Projects
- Click your Project
- Check the Header

## Expected Behavior

- The header should not be adjacent to each other so that there is space

**Comment by jsvelte** [comment]
close #35
