### ISSUE TITLE
Sidebar Persisted State

### ISSUE THREAD

**Issue by ipilikent** [abduljalilpalala/ps-slackana#29]
## Description

- Close the sidebar and click on the board and chat the sidebar will pop up

![No sidebar will pop up when click board and chat](https://user-images.githubusercontent.com/110364019/193532715-bbf0f784-f7aa-411b-882a-9227bda997de.gif)

## Expected Behavior

- The sidebar should not appear when close and click on the board and chat

**Comment by jsvelte** [comment]
close #35
